export const programmingLanguageExtensions: { [key: string]: string } = {
    "C++": "cpp",
    "Java": "java",
    "Python": "py",
    "Python3": "py",
    "C": "c",
    "C#": "cs",
    "JavaScript": "js",
    "TypeScript": "ts",
    "PHP": "php",
    "Swift": "swift",
    "Kotlin": "kt",
    "Dart": "dart",
    "Go": "go",
    "Ruby": "rb",
    "Scala": "scala",
    "Rust": "rs",
    "Racket": "rkt",
    "Erlang": "erl",
    "Elixir": "ex",
    "Pandas": "py",
    "MySQL": "sql",
    "MS SQL Server": "sql",
    "Oracle": "sql",
    "PostgreSQL": "sql",
};